name = "nemesis-edge-proxy"
main = "cloudflare_worker/src/index.ts"
compatibility_date = "2024-12-01"

[observability]
enabled = true

[[kv_namespaces]]
binding = "NEMESIS_KV"
id = "556aa273aeac4b009b559bb215346ce3"
preview_id = "556aa273aeac4b009b559bb215346ce3"

[[d1_databases]]
binding = "DB"
database_name = "nemesis_audit_db"
database_id = "556aa273aeac4b009b559bb215346ce3"

[[r2_buckets]]
binding = "NEMESIS_STORAGE"
bucket_name = "nemesis-assets"

[vars]
BACKEND_API_URL = "https://nemesis-backend.onrender.com"
