name = "nemesis-edge-proxy"
main = "cloudflare_worker/src/index.ts"
compatibility_date = "2024-12-01"

[observability]
enabled = true

[[kv_namespaces]]
binding = "NEMESIS_KV"
id = "556aa273aeac4b009b559bb215346ce3"
preview_id = "556aa273aeac4b009b559bb215346ce3"

[[d1_databases]]
binding = "DB"
database_name = "nemesis_audit_db"
database_id = "80acedab-33c2-4637-bee7-6b9a1176a463"

[[r2_buckets]]
binding = "NEMESIS_STORAGE"
bucket_name = "nemesis-assets"

[vars]
BACKEND_API_URL = "https://nemesis-local.onrender.com"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "2bf62864eaf64708b5a349169d6efc7e"
localConnectionString = "postgresql://admin:!Nemesis2026@ep-morning-glitter-adpz0uqn-pooler.c-2.us-east-1.aws.neon.tech:5432/intelligence?sslmode=require"

