name = "nemesis-loc-backend"
main = "app/main.py"
compatibility_date = "2024-03-20"
compatibility_flags = ["python_workers"]

# Cloudflare Bindings
[[d1_databases]]
binding = "DB"
database_name = "nemesis"
database_id = "73ef6e7d-9499-4d59-a190-ae7220873a71"

[[kv_namespaces]]
binding = "NEMESIS_CACHE"
id = "f4099ea1458e4e62ba838734f172846f"

[vars]
APP_MODE = "production"
