name = "nemesis-loc-backend"
main = "app/main.py"
compatibility_date = "2024-03-20"
compatibility_flags = ["python_workers"]

# Cloudflare Bindings
[[d1_databases]]
binding = "DB"
database_name = "nemesis"
database_id = "73ef6e7d-9499-4d59-a190-ae7220873a71"

[[d1_databases]]
binding = "AUDIT_DB"
database_name = "nemesis_audit_db"
database_id = "80acedab-33c2-4637-bee7-6b9a1176a463"

[[d1_databases]]
binding = "NEMESIS_DB"
database_name = "nemesis-db"
database_id = "860655f8-aa37-4d4f-92a9-b5ea49bc101a"

[[kv_namespaces]]
binding = "NEMESIS_CACHE"
id = "f4099ea1458e4e62ba838734f172846f"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "2bf62864eaf64708b5a349169d6efc7e"
localConnectionString = "postgresql://admin:!Nemesis2026@ep-morning-glitter-adpz0uqn-pooler.c-2.us-east-1.aws.neon.tech:5432/intelligence"

[vars]
APP_MODE = "production"
